apiVersion: v1
kind: Service
metadata:
  name: quiz-app-frontend-svc
  labels:
    app: quiz-app-frontend
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: quiz-app-frontend
  type: LoadBalancer
